[package]
name = "proxy"
version = "0.1.0"
authors = ["zhangzheng <zhangzheng@aengine.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
tracing = "0.1"
tracing-subscriber = "0.2"